<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}

@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}

@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}

@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}

.navbar-default {
    background: #FF7F50;
    border: none;
    height: 45px;
    box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);
}

.navbar-nav.left_part_header .search-container {
    background: #FF7F50;
}

.round-check input[type="checkbox"]:checked+label:before {
    background: #FF7F50 !important;
}

.group-messages-wrapper a {
    color: #FF7F50 !important;
}

ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: #FF7F50 !important;
}

.featured-users {
    background: #fff !important;
}

.result-bar {
    background: #FF7F50 !important;
}

.avtive {
    border-color: #FF7F50 !important;
}

.left-sidebar ul li a i {
    color: #FF7F50 !important;
}

.cs-loader-inner,
.main {
    color: #FF7F50;
}

.login input:focus,
ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper {
    border-color: #FF7F50 !important;
}

.login:not(.loading) button:hover {
    background: #2e7be5 !important;
    color: #ffffff;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle {
    border-color: #FF7F50;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after {
    background: #FF7F50;
}

.login button,
.wo_search_page .nav-tabs li.active a {
    background: #FF7F50 !important;
    color: #ffffff !important;
}

.mejs-controls .mejs-time-rail .mejs-time-current,
.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current,
.mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: #FF7F50 !important;
    background: #FF7F50 !important;
    background-image: #FF7F50 !important;
}

.navbar-default .navbar-nav>.open>a,
.navbar-default .navbar-nav>.open>a:focus,
.navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];
    ?> !important;
    background-color: #2e7be5 !important;
}

.navbar-default .navbar-nav>.active>a,
.navbar-default .navbar-nav>.active>a:focus,
.navbar-default .navbar-nav>.active>a:hover,
.nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];
    ?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];
    ?> !important;
}

body {
    background-color: <?php echo $wo['config']['body_background'];
    ?>;
}

.navbar-default .navbar-nav>li>a {
    color: <?php echo $wo['config']['header_color'];
    ?>;
    font-size: 13px;
}

a.unread-update,
.head_clos_srch {
    color: <?php echo $wo['config']['header_color'];
    ?> !important;
}

.btn-main {
    color: #ffffff;
    background-color: #FF7F50;
    border-color: #FF7F50;
}

.btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];
    ?>;
    background-color: #2e7be5;
    border-color: #2e7be5;
}

.active-wonder {
    color: #FF7F50;
}

.admin-panel .col-md-9 .list-group-item:first-child,
.setting-panel .col-md-8 .list-group-item:first-child,
.profile-lists .list-group-item:first-child,
.col-md-8 .list-group-item:first-child,
.col-md-3.custom .list-group-item:first-child,
.col-sm-4 .list-group-item:first-child,
.col-md-7 .list-group-item:first-child,
.col-md-9 .list-group-item:first-child,
.red-list .list-group-item:first-child,
.active.list-group-item:first-child {
    color: #444;
    background-color: #fcfcfc;
    border-bottom: 1px solid #f1f1f1;
    padding: 18px;
}

.admin-panel .col-md-9 .list-group-item:first-child a,
.setting-panel .col-md-8 .list-group-item:first-child a,
.profile-lists .list-group-item:first-child a,
.col-md-8 .list-group-item:first-child a,
.col-md-7 .list-group-item:first-child a,
.active.list-group-item:first-child a {
    color: #444 !important;
}

.list-group-item.black-list.active-list,
.red-list.active-list {
    color: #ffffff;
    background-color: #FF7F50;
}

.list-group-item.black-list {
    background: #FF7F50;
}

.profile-top-line {
    background-color: #FF7F50;
}

#bar {
    background-color: #FF7F50;
}

.list-group-item.black-list a {
    color: #ffffff;
}

.list-group-item.black-list.active-list a {
    color: #FF7F50;
}

.main-color,
.small-text a {
    color: #FF7F50 !important;
}

.nav-tabs>li.active>a,
.nav-tabs>li.active>a:focus,
.nav-tabs>li.active>a:hover {
    color: #ffffff;
    cursor: default;
    color: #FF7F50;
    border-bottom: 1px solid #FF7F50;
    background-color: transparent
}

.btn-active {
    color: #ffffff;
    background: #FF7F50;
    outline: none;
    border: 1px solid #FF7F50
}

.btn-active:hover,
.btn-active:focus {
    border: 1px solid #2e7be5;
    color: <?php echo $wo['config']['btn_hover_color'];
    ?>;
    background: #2e7be5;
}

.btn-active-color:hover {
    background: #2e7be5;
}

.chat-tab .online-toggle {
    background: #FF7F50;
}

.profile-style .user-follow-button button.btn-active,
.btn-login,
.btn-register {
    background: #FF7F50;
    color: #ffffff;
}

.profile-style .user-follow-button button.btn-active:hover,
.btn-login:hover,
.btn-login:focus,
.btn-register:hover,
.btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];
    ?>;
    background: #2e7be5;
}

.panel-login>.panel-heading a.active {
    color: #FF7F50;
    font-size: 18px;
}

.hash {
    color: #FF7F50;
}

.message-text .hash {
    color: #fff !important;
}

.search-container .search-input {
    color: #fff !important;
    background: #0147a9 !important;
}

.chat-messages-wrapper .outgoing {
    background: #FF7F50;
}

.message p {
    color: #fff;
}

.text-sender-container .outgoing .message-model .message {
    background: #FF7F50;
}

.incoming .message. p {
    color: #555;
}

.incoming.message p {
    color: #555;
}

.incoming .message p {
    color: #555;
}

.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}

.active.fa-thumbs-up {
    color: #FF7F50;
}

.api-ex-urls {
    background-color: #FF7F50;
    color: #ffffff;
}

.user-username {
    color: #FF7F50;
}

.upload-image {
    border: 3px dashed #FF7F50;
}

.events-tab-list li {
    background-color: #FF7F50;
}

.events-tab-list li:hover {
    background-color: #FF7F50;
}

.active-e-tab {
    background-color: #FF7F50 !important;
}

.main {
    color: #FF7F50 !important;
}

.events-list-dropup-menu ul li a:hover {
    background: #FF7F50;
}

.usr-offline {
    color: #FF7F50;
}

.blog-dd-ul li span:hover,
.blog-dd-ul li a:hover {
    background: #FF7F50 !important;
}

.blog_publ {
    background: #FF7F50;
    border: 1px solid #FF7F50;
}

.slide-film-desc:hover,
.movies-top-breadcrumb li:hover,
.movies-top-breadcrumb li a:hover {
    color: #FF7F50 !important;
}

.movies h3.latest-movies,
h3.recommended-movies {
    border-left: 3px solid #FF7F50;
}

.wo_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 2px solid #FF7F50;
    color: #FF7F50;
}


<?php if ($wo['config']['chatSystem']==1 && $wo['page'] !='get_news_feed'&& $wo['page'] !='welcome'&& $wo['page'] !='404'&& $wo['page'] !='movies'&& $wo['loggedin']==true && $wo['page'] !='messages'&& $wo['page'] !='start_up') {

    ?>body,
    .navbar-default,
    .wo_about_wrapper_parent {
        padding-right: 205px;
    }

    @media (min-width: 1420px) {

        body,
        .navbar-default,
        .wo_about_wrapper_parent {
            padding-right: 240px;
        }

        .sun_blog_head {
            right: 240px;
        }
    }

    @media (max-width:1140px) {
        .wo_about_wrapper_parent {
            padding-right: 0px;
        }
    }

    .sun_blog_head {
        right: 205px;
    }

    <?php
}

?><?php if($wo['language_type']=='rtl'&& $wo['config']['chatSystem']==1 && $wo['page'] !='get_news_feed'&& $wo['page'] !='welcome'&& $wo['page'] !='404'&& $wo['page'] !='movies'&& $wo['page'] !='messages'&& $wo['page'] !='start_up'&& $wo['loggedin']==true) {

    ?>body,
    .navbar-default,
    .wo_about_wrapper_parent {
        padding-left: 205px;
        padding-right: 0px;
    }

    @media (max-width:1140px) {
        .wo_about_wrapper_parent {
            padding-left: 0px;
        }
    }

    <?php
}

?>.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px #FF7F50 !important;
}

.ui-widget-header .ui-state-default {
    background-color: #FF7F50;
}

<?php if ( !empty($wo['reactions_types'])) {
    foreach ($wo['reactions_types'] as $key=> $value) {
        ?>.reaction-<?php echo $value['id'];

        ?>::before {
            content: "<?php echo $value['name'];?>";
        }

        <?php
    }
}

?>
/*.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}*/

.navbar-default .dropdown-menu.ani-acc-menu>li>a:hover {
    color: #ffffff;
    background-color: #FF7F50;
}

@media (min-width: 992px) {
    #wo_msg_right_prt .text-sender-container .outgoing .message-model .message p {
        color: #ffffff;
        background-color: #FF7F50;
    }

    #wo_nw_msg_page .messages-recipients-list .msg_ava_name {
        color: <?php echo $wo['config']['header_color'];
        ?> !important;
    }

    #wo_nw_msg_page .messages-recipients-list.active .msg_ava_name {
        color: #333 !important;
    }
}

<?php if ($wo['config']['google_map']==0) {
    ?>#filterby-post li {
        width: 16.5%;
    }

    <?php
}

?>.sun_input input:focus,
.sun_input textarea:focus,
.sun_input select:focus {
    border-color: #FF7F50
}

.loading::before {
    background-color: #FF7F50;
}

<?php if($wo['page']=='home') {
    ?>#wo_post_stat_button>.stat-item:nth-child(2) svg {
        margin-right: 3px;
    }

    <?php
}

?><?php if($wo['language']=='russian') {
    ?>.wo_market .market_bottom .product .product-links .info-middle .more-info {
        padding: 0px 15px;
        margin: 0px 3px;
    }

    <?php
}

?><?php if($wo['language']=='spanish') {
    ?>@media (min-width: 600px) {
        .sun_pub_mid_foot .poster-left-buttons:last-child {
            max-width: 100px;
        }

        .sun_pub_mid_foot .poster-left-buttons:last-child .btn {
            max-width: 100px;
        }

        .sun_pub_mid_foot .poster-left-buttons:last-child .btn span {
            max-width: calc(100% - 22px);
            display: inline-block;
            overflow: hidden;
            text-overflow: ellipsis;
            vertical-align: bottom;
        }
    }

    <?php
}

?>

</style>
